const express=require('express')
const app=express();

const cors=require('cors')


app.use(cors())
app.post('/',(req,res)=>{
    res.send({name:'gjk'})
    console.log(res)
    
})
app.post('/bollywood',(req,res)=>{
    res.send([{ Id: 1, img: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5b/Attack_film_poster.jpg/220px-Attack_film_poster.jpg', h2: "John Abraham in Attack", p: `John Abraham is an Indian actor, film producer and former model who appears in Hindi films. After modelling for numerous advertisements and companies, he made his film debut with Jism, earning a Filmfare Award for Best Male Debut nomination.`, h3: 'Bollywood ', span: 'Janvary 24,2022' },
    { Id: 2, img: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Antim-_The_Final_Truth.jpg', h2: 'Aayush Sharma in Antim:The Final Truth', p: `A man from humble origins works his way up to an influential position within organised crime. Nothing seems able to stop him until he runs into a police officer who takes his job to uphold justice very seriously.`, h3: 'Bollywood ', span: 'February 24, 2022' },
    { Id: 3, img: 'https://images.news18.com/ibnlive/uploads/2021/07/1625839961_farhan-akhtar.jpg?impolicy=website&width=510&height=356', h2: 'Farhan Aktar in Toofan', p: `Toofaan is a 2021 Indian Hindi-language sports drama film directed and produced by Rakeysh Omprakash Mehra, produced by Ritesh Sidhwani under Excel Entertainment and ROMP Pictures and starring producer Farhan Akhtar as a national level boxer alongside Mrunal Thakur and Paresh Rawal in the lead roles.`, h3: 'Bollywood', span: 'Janvary 2,2022' },
    { Id: 4, img: 'https://cdn.gulte.com/wp-content/uploads/2021/12/Review1.jpg', h2: 'Allu Arjun in Pushpa:The Rise', p: 'Allu Arjun is an Indian actor who predominantly works in Telugu films. He is one of the highest paid actors in South India and known for his dancing abilities, Allu is a recipient of several awards, including five Filmfare Awards South and five Nandi Awards.', h3: 'Bollywood ', span: 'March 14,2022' },
    { Id: 5, img: "https://m.media-amazon.com/images/M/MV5BZmM4ZGNmZTgtNDllNi00MzUxLTg5NjQtZjdmMDEyMWVlY2E4XkEyXkFqcGdeQXNuZXNodQ@@._V1_.jpg", h2: 'Parineeti Chopra in saina', p: `Saina Nehwal, a badminton enthusiast, considers pursuing the sport full-time. When she starts training under an efficient coach, she soon becomes the best and ranks number one in the sport.`, h3: 'Bollywood ', span: 'Februry 24,2022' }])
    // console.log(res)   
})
app.post('/fitness',(req,res)=>{
    res.send([{ Id: 1, img: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', h2: "Sweat now shine later", p: `Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.`, h3: 'Fitness ', span: 'Janvary 24,2022' },
    { Id: 2, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSrdf6g7uniI6jBGZblgSvfdGwaNqwS6U53w&usqp=CAU', h2: 'Balance', p: `Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.`, h3: 'Fitness ', span: 'February 24, 2022' },
    { Id: 3, img: 'https://s3.envato.com/files/326194671/DSC_4013.jpg', h2: 'Aerobic', p: `Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.`, h3: 'Fitness', span: 'Janvary 2,2022' },
    { Id: 4, img: 'https://image.shutterstock.com/image-photo/woman-exercise-workout-gym-fitness-260nw-749969473.jpg', h2: 'Sprint', p: 'Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.', h3: 'Fitness ', span: 'March 14,2022' },
    { Id: 5, img: 'https://fitnessone.in/img/gallery/about.png', h2: 'Flexibility', p: `Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.`, h3: 'Fitness ', span: 'Februry 24,2022' }])
    // console.log(res)   
})
app.post('/food',(req,res)=>{
    res.send([{ Id: 1, img: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-chicken-tikka-masala-jpg-1526059261.jpg', h2: "Chiken Tikka Masala", p: `Chicken tikka masala is a dish consisting of roasted marinated chicken chunks in spiced curry sauce. The curry is usually creamy and orange-coloured. The dish was popularized by cooks from the Indian subcontinent living in Great Britain and is offered at restaurants around the world.`, h3: 'Food ', span: 'Janvary 24,2022' },
    { Id: 2, img: 'https://www.cookwithmanali.com/wp-content/uploads/2015/07/Restaurant-Style-Recipe-Paneer-Tikka.jpg', h2: 'Pneer Tikka', p: `Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor. It is a vegetarian alternative to chicken tikka and other meat dishes. It is a popular dish that is widely available in India and countries with an Indian diaspora.`, h3: 'Food ', span: 'February 24, 2022' },
    { Id: 3, img: 'https://i0.wp.com/cdn.whatsuplife.in/kolkata/blog/2019/11/6ballygunge.jpg', h2: 'Maach Bhaat', p: `Think Bengali cuisine and the first thing that comes to mind is maach bhaat or roshogolla and mishti doi. It’s sad how Bengali cuisine has been stereotyped to be just that. In reality, there’s so much more. It’s about time we bust the myths and let the world know that it’s not as fishy and sugary as one thinks.`, h3: 'Food', span: 'Janvary 2,2022' },
    { Id: 4, img: 'https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa-500x500.jpg', h2: 'Masala Dosa', p: 'Masala dosa is a variation of the popular South Indian dosa, which has its origins in Tuluva Udupi cuisine of Karnataka. It is made from rice, lentils, potato, fenugreek, ghee and curry leaves, and served with chutneys and sambar. ', h3: 'Food ', span: 'March 14,2022' },
    { Id: 5, img: "https://www.cookwithmanali.com/wp-content/uploads/2020/03/Malai-Kofta-Recipe.jpg", h2: 'Malai Kofta', p: `Kofta is a Middle Eastern dish made from ground lamb or beef mixed with onions, garlic, and spices. The meat mixture is shaped into balls, patties or logs, and then grilled and served with pita, salads, dips, and sauces.`, h3: 'Food ', span: 'Februry 24,2022' }])
})
app.post('/technology',(req,res)=>{
   res.send([{ Id: 1, img: 'https://imageio.forbes.com/specials-images/imageserve/60269ef7ada7085ce688069b/Cyber-Security-and-Digital-Data-Protection-Concept/960x0.jpg?fit=bounds&format=jpg&width=960', h2: "Cyber Security:Prevention is better than cure", p: `Computer security, cybersecurity, or information technology security is the protection of computer systems and networks from information disclosure, theft of or damage to their hardware, software, or electronic data, as well as from the disruption or misdirection of the services they provide.`, h3: 'Technology ', span: 'Janvary 24,2022' },
   { Id: 2, img: 'https://www.cyberbahnit.com/wp-content/uploads/2017/11/blockchain.jpg', h2: 'Blockchain', p: `A blockchain game is a video game that includes elements that use cryptography-based blockchain technologies.`, h3: 'Technology ', span: 'February 24, 2022' },
   { Id: 3, img: 'https://images.idgesg.net/images/article/2017/05/artificial_intelligence_machine_learning_network_thinkstock_671750598-100724432-large.jpg?auto=webp&quality=85,70', h2: 'Artifical inteligent (AI) & Machine Learning ', p: `Artificial intelligence and machine learning are the part of computer science that are correlated with each other. These two technologies are the most trending technologies which are used for creating intelligent systems.Although these are two related technologies and sometimes people use them as a synonym for each other, but still both are the two different terms in various cases.`, h3: 'Technology', span: 'September 31,2022' },
   { Id: 4, img: 'https://www.control4.com/files/large/b9d80879aba75c9', h2: 'Internet of Thing (IOT)', p: 'The Internet of things describes physical objects that are embedded with sensors, processing ability, software, and other technologies that connect and exchange data with other devices and systems over the Internet or other communications networks.', h3: 'Technology ', span: 'March 14,2022' },
   { Id: 5, img: "https://cf-assets.www.cloudflare.com/slt3lc6tev37/5UFGteYwYTmakGi1m4hh10/68451375d91f71ce26ebbe4bb8051f04/cryptographic-key.png", h2: 'Cryptography', p: `Cryptography, or cryptology, is the practice and study of techniques for secure communication in the presence of adversarial behavior.`, h3: 'Technology ', span: 'Februry 24,2022' }]) 
})
app.post('/tourism',(req,res)=>{
    res.send([{ Id: 1, img: 'https://images.moneycontrol.com/static-mcnews/2021/08/Kerala-toursim-770x433.jpg', h2: "Kerala: God's Own Country", p: `Kerala, a state situated on the tropical Malabar Coast of southwestern India,'is one of the most popular tourist destinations in the countryNamed as one of the ten paradises of the world by National Geographic Traveler, Kerala is famous especially for its ecotourism initiatives and beautiful backwaters.`, h3: 'Tourism ', span: 'Janvary 24,2022' },
    { Id: 2, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZPyRZHXLeXT6OxmDQdU2AtwWKGN_xHzf_IA&usqp=CAU', h2: 'Madhya Pradesh:The Heart of Incredible India', p: `Madhya Pradesh, a large state in central India, retains landmarks from eras throughout Indian history.Begun in the 10th century, its Hindu and Jain temples at Khajuraho are renowned for theircarvings of erotic scenes, most prominently Kandariya Mahadeva,a temple with more than 800 sculptures.`, h3: 'Tourism ', span: 'February 24, 2022' },
    { Id: 3, img: 'https://www.deccanherald.com/sites/dh/files/styles/article_detail/public/articleimages/2020/10/25/file77vf0pn8ouod3o2ghgf-906630-1603571712.jpg?itok=0QRkAjVH', h2: 'Karnataka: One state Many Worids', p: `Karnataka is a state in southwest India with Arabian Sea coastlines. The capital, Bengaluru (formerly Bangalore), is a high-tech hub known for its shopping and nightlife. To the southwest, Mysore is home to lavish temples including Mysore Palace, former seat of the region’s maharajas.`, h3: 'Tourism', span: 'Janvary 2,2022' },
    { Id: 4, img: 'https://media.easemytrip.com/media/Blog/India/637350613416802581/637350613416802581qElw1X.png', h2: 'Sikkim: Small But Beautiful', p: 'Sikkim is a state in northeast India, bordered by Bhutan, Tibet and Nepal. Part of the Himalayas, the area has a dramatic landscape that includes India’s highest mountain, 8,586m Kangchenjunga. Sikkim is also home to glaciers, alpine meadows and thousands of varieties of wildflowers.', h3: 'Tourism ', span: 'March 14,2022' },
    { Id: 5, img: "https://assets.traveltriangle.com/blog/wp-content/uploads/2018/07/amritsar-3083693_960_720.jpg", h2: 'Punjab: India Begin Here', p: `Punjab, a state bordering Pakistan, is the heart of India’s Sikh community. The city of Amritsar, founded in the 1570s by Sikh Guru Ram Das, is the site of Harmandir Sahib, the holiest gurdwara (Sikh place of worship). Known in English as the Golden Temple, and surrounded by the Pool of Nectar, it's a major pilgrimage site.`, h3: 'Tourism ', span: 'Februry 24,2022' }])
})
app.post('/article',(req,res)=>{
    res.send([{ Id: 4, img: "https://assets.traveltriangle.com/blog/wp-content/uploads/2018/07/amritsar-3083693_960_720.jpg", h2: 'Punjab: India Begin Here', p: `Punjab, a state bordering Pakistan, is the heart of India’s Sikh community. The city of Amritsar, founded in the 1570s by Sikh Guru Ram Das, is the site of Harmandir Sahib, the holiest gurdwara (Sikh place of worship). Known in English as the Golden Temple, and surrounded by the Pool of Nectar, it's a major pilgrimage site.`, h3: 'Tourism ', span: 'Februry 24,2022' },
    { Id: 5, img: "https://cf-assets.www.cloudflare.com/slt3lc6tev37/5UFGteYwYTmakGi1m4hh10/68451375d91f71ce26ebbe4bb8051f04/cryptographic-key.png", h2: 'Cryptography', p: `Cryptography, or cryptology, is the practice and study of techniques for secure communication in the presence of adversarial behavior.`, h3: 'Technology ', span: 'Februry 24,2022' },
    { Id: 6, img: "https://m.media-amazon.com/images/M/MV5BZmM4ZGNmZTgtNDllNi00MzUxLTg5NjQtZjdmMDEyMWVlY2E4XkEyXkFqcGdeQXNuZXNodQ@@._V1_.jpg", h2: 'Parineeti Chopra in saina', p: `Saina Nehwal, a badminton enthusiast, considers pursuing the sport full-time. When she starts training under an efficient coach, she soon becomes the best and ranks number one in the sport.`, h3: 'Bollywood ', span: 'Februry 24,2022' },
    { Id: 7, img: "https://www.cookwithmanali.com/wp-content/uploads/2020/03/Malai-Kofta-Recipe.jpg", h2: 'Malai Kofta', p: `Kofta is a Middle Eastern dish made from ground lamb or beef mixed with onions, garlic, and spices. The meat mixture is shaped into balls, patties or logs, and then grilled and served with pita, salads, dips, and sauces.`, h3: 'Food ', span: 'Februry 24,2022' }])
})
app.post('/latest',(req,res)=>{
    res.send([{ Id: 1, img: 'https://s3.envato.com/files/326194671/DSC_4013.jpg', h2: 'Aerobic', p: `Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.`, h3: 'Fitness', span: 'Janvary 2,2022' },
    { Id: 2, img: 'https://images.news18.com/ibnlive/uploads/2021/07/1625839961_farhan-akhtar.jpg?impolicy=website&width=510&height=356', h2: 'Farhan Aktar in Toofan', p: `Toofaan is a 2021 Indian Hindi-language sports drama film directed and produced by Rakeysh Omprakash Mehra, produced by Ritesh Sidhwani under Excel Entertainment and ROMP Pictures and starring producer Farhan Akhtar as a national level boxer alongside Mrunal Thakur and Paresh Rawal in the lead roles.`, h3: 'Bollywood', span: 'Janvary 2,2022' },
    { Id: 3, img: 'https://www.cookwithmanali.com/wp-content/uploads/2015/07/Restaurant-Style-Recipe-Paneer-Tikka.jpg', h2: 'Pneer Tikka', p: `Paneer tikka is an Indian dish made from chunks of paneer marinated in spices and grilled in a tandoor. It is a vegetarian alternative to chicken tikka and other meat dishes. It is a popular dish that is widely available in India and countries with an Indian diaspora.`, h3: 'Food ', span: 'February 24, 2022' }])
})
app.post('/side',(req,res)=>{
    res.send([{ Id: 8, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZPyRZHXLeXT6OxmDQdU2AtwWKGN_xHzf_IA&usqp=CAU', h2: 'Madhya Pradesh:The Heart of Incredible India', h3: 'Tourism ', span: 'February 24, 2022' },
    { Id: 9, img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSrdf6g7uniI6jBGZblgSvfdGwaNqwS6U53w&usqp=CAU', h2: 'Balance', h3: 'Fitness ', span: 'February 24, 2022' },
    { Id: 10, img: 'https://www.cyberbahnit.com/wp-content/uploads/2017/11/blockchain.jpg', h2: 'Blockchain', h3: 'Technology ', span: 'February 24, 2022' },
    { Id: 11, img: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Antim-_The_Final_Truth.jpg', h2: 'Aayush Sharma in Antim:The Final Truth', h3: 'Bollywood ', span: 'February 24, 2022' },
    { Id: 12, img: 'https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa-500x500.jpg', h2: 'Masala Dosa', h3: 'Food ', span: 'March 14,2022' }])
})
app.listen(5000,()=>{
    console.log('server is running....')
})
